version: '3.2'

# variables d'environnement avec secrets, et noms spéciques des machines de production

# avec un montage nfs des données de synchronisation
volumes:
  geosync_dev_ouvert:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.74.148,nolock,soft,rw"
      device: ":/nfs/docker/georchestra/geosync_dev_ouvert/owncloudsync"
  geosync_dev_restreint:
    driver_opts:
      type: "nfs"
      o: "addr=172.20.74.148,nolock,soft,rw"
      device: ":/nfs/docker/georchestra/geosync_dev_restreint/owncloudsync"

services:

  ldap:
    environment:
      - AD_DOMAIN=umrthema.univ-fcomte.fr
      - AD_DC_STRING=dc=umrthema,dc=univ-fcomte,dc=fr
      - AD_SERVER=thema-serv3.umrthema.univ-fcomte.fr
      - AD_PASSWORD=1\@gustiNE6
      # - TESTADMIN_PASSWORD=AdminTest
      # le même mot de passe passé par la commande slappasswd
      - TESTADMIN_PASSWORD={SSHA}Hli5mlq0JytMrC4yXQYNswWDTbcFOGaM
    extra_hosts:
      - "thema-serv3.umrthema.univ-fcomte.fr:172.20.74.170"

  geosync:
    environment:
      - OPEN_USER_DAVPASS=Lesoleilauzenith
      - RSCT_USER_DAVPASS=Lesoleilauzenith

  proxy:
    labels:
      - "traefik.frontend.rule=Host:georchestra-docker.umrthema.univ-fcomte.fr"
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"

  cas:
    labels:
      - "traefik.frontend.rule=Host:georchestra-docker.umrthema.univ-fcomte.fr;PathPrefix:/cas"
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"

  geosync:
    environment:
      - SERVER_URL=https://georchestra-docker.umrthema.univ-fcomte.fr
      - OCL_URL=https://owncloud-mshe.univ-fcomte.fr
    #volumes:
      # avec montage nfs
      #- type: volume
      #  source: geosync_dev_ouvert
      #  target: /mnt/geosync_ouvert/owncloudsync
      #  volume:
      #    nocopy: true
      #- /docker/georchestra/geosync_dev_restreint:/mnt/geosync_restreint/owncloudsync
      #- type: volume
      #  source: geosync_dev_restreint
      #  target: /mnt/geosync_restreint/owncloudsync
      #  volume:
      #    nocopy: true

    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"

  geoserver:
    # pour envoyer des données au geoserver avec son UI
    #volumes:
    #  - type : volume
    #    source : geosync_dev_ouvert
    #    target : /mnt/geosync_ouvert
    #  - type : volume
    #    source : geosync_dev_restreint
    #    target : /mnt/geosync_restreint
    environment:
      - SERVER_URL=https://georchestra-docker.umrthema.univ-fcomte.fr
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"

  geonetwork:
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"

