version: "3.2"

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

volumes:
  smtp_maildir:

services:
  georchestra.mydomain.org:
    image: traefik:1.4.5
    ports:
      - "80:80"
      - "443:443"
      # uncomment the next line to get a web ui + api at https://georchestra.mydomain.org:8080/traefik/
      #- "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/ssl:/etc/traefik/ssl/
      - ./resources/traefik.toml:/traefik.toml

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      # label de production déplacé dans docker-compose.geosync-prod.yml
      # - "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"

  cas:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cas"
      # label de production déplacé dans docker-compose.geosync-prod.yml
      # - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/cas"

  smtp:
    image: camptocamp/smtp-sink:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/

  ssh:
    build: ../georchestra/docker/ssh_data
    image: georchestra/ssh_data:latest
    environment:
      - TZ=Europe/Paris
    ports:
      - "2222:22"
    volumes:
      - geoserver_geodata:/mnt/geoserver_geodata
      - /docker/georchestra/geoserver_geodata:/mnt/geoserver_geodata

  geosync:
    build: ../georchestra/geosync
    image: geosync/geosync
    depends_on:
      - ldap
      - database
      - geoserver
      - geonetwork
    environment:
      - TZ=Europe/Paris
      # variables de production déplacées dans docker-compose.geosync-prod.yml
      #- SERVER_URL=https://georchestra.mydomain.org
      #- OCL_URL=https://owncloud.mydomain.org
    volumes:
      - /docker/georchestra/georchestra_ouvert:/home/georchestra-ouvert
      - /docker/georchestra/georchestra_restreint:/home/georchestra-restreint
      # volumes déplacés dans docker-compose.geosync-prod.yml pour un montage NFS
      #- /docker/georchestra/geosync_dev_ouvert:/mnt/geosync_ouvert/owncloudsync
      #- /docker/georchestra/geosync_dev_restreint:/mnt/geosync_restreint/owncloudsync
    restart: always

