version: "3.2"

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

volumes:
  smtp_maildir:

services:
  georchestra-dev.umrthema.univ-fcomte.fr:
    image: traefik:1.4.5
    ports:
      - "80:80"
      - "443:443"
      # uncomment the next line to get a web ui + api at https://georchestra-dev.umrthema.univ-fcomte.fr:8080/traefik/
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/ssl:/etc/traefik/ssl/
      # fichier de production défini dans docker-compose.geosync-prod.yml
      #- ./resources/traefik.toml:/traefik.toml

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      # label de production déplacé dans docker-compose.geosync-prod.yml
      # - "traefik.frontend.rule=Host:georchestra-dev.umrthema.univ-fcomte.fr"
      - "traefik.frontend.passHostHeader=true"

  cas:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cas"
      # label de production déplacé dans docker-compose.geosync-prod.yml
      # - "traefik.frontend.rule=Host:georchestra-dev.umrthema.univ-fcomte.fr;PathPrefix:/cas"

  smtp:
    image: camptocamp/smtp-sink:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/

#  ssh:
#    image: georchestra/ssh_data:latest
#    environment:
#      - TZ=Europe/Paris
#    ports:
#      - "2222:22"
#    volumes:
#      - geoserver_geodata:/mnt/geoserver_geodata
#      - /docker/georchestra/geoserver_geodata:/mnt/geoserver_geodata

